language: node_js
node_js:
    - '13'

stages:
    - build
    - test
    - lint

jobs:
    include:
        - stage: build
          script:
            - cd backend
            - npm install
            - npm start
        - stage: build
          script:
            - cd frontend
            - npm install
            - npm run build
        - stage: test
          script:
            - cd backend
            - npm install
            - npm run test
        - stage: test
          script:
            - cd frontend
            - npm install
            - npm run test
        - stage: lint
          script:
            - cd backend
            - npm install
            - npm run lint
        - stage: build
          script:
            - cd frontend
            - npm install
            - npm run lint
